# Automatically assign labels to PRs based on files changed

name: pull-request-labeler
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/pull-request-labeler.yaml
        sync-labels: true
