name: build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.[a-z]+'
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch pre-commit cookiecutter
        hatch env create
    - name: Render cookiecutter template
      run: |
        git config --global user.email "noone@example.com"
        git config --global user.name "No One"
        mkdir -p build && cd build
        cookiecutter --no-input ..
        cd python-cli-app
    - name: Build application
      run: |
        cd build/python-cli-app
        hatch build
        hatch clean
    - name: Build documentation
      run: |
        cd build/python-cli-app
        hatch run docs:build-check
    - name: Pre-commit checks
      run: |
        cd build/python-cli-app
        hatch run pre-commit run
    - name: Lint
      run: |
        cd build/python-cli-app
        hatch run lint:all
    - name: Test
      run: |
        cd build/python-cli-app
        hatch run test:no-cov
    - name: Run application commands
      run: |
        cd build/python-cli-app
        hatch run pca --version
        hatch run pca prime 100
        hatch run pca config show --show-origin
    - name: Clean environments
      run: |
        cd build/python-cli-app
        hatch env prune
